### ISSUE TITLE
[feat] more `weback@5` and `vite` friendly

### ISSUE THREAD

**Issue by JounQin** [inspect-js/available-typed-arrays#12]
Like https://github.com/inspect-js/has-symbols/issues/11#issuecomment-787098519

https://github.com/inspect-js/available-typed-arrays/blob/main/index.js#L20

**Comment by ljharb** [comment]
In this case, that isn't an option, because we're dynamically looking up a global variable.

This is just a case where webpack 5 and vite will either remain broken, forcing their users to fix it, or else they can fix their bug, and provide `global` (especially since it's literally `global=globalThis;` at the top of bundle output to fix it).

**Comment by JounQin** [comment]
@ljharb 

Can we use:

```ts
const g = typeof globalThis === 'undefined' ? global : globalThis

// use `g` after
```

**Comment by ljharb** [comment]
I suppose we could, altho that's adding a bundle cost for all the people using a non-broken bundler, which is the vast majority.

**Comment by JounQin** [comment]
> I suppose we could, altho that's adding a bundle cost for all the people using a non-broken bundler, which is the vast majority.

Hmm... It seems only 60 bytes more, including spaces. Shall I raise a PR?

**Comment by ljharb** [comment]
Sure, I suppose that's fine.

**Comment by JounQin** [comment]
@ljharb See #13
