### ISSUE TITLE
`global` breaks browser builds

### ISSUE THREAD

**Issue by aryzing** [inspect-js/available-typed-arrays#8]
When this package makes its way to the browser (ie, as part of [`util`](https://github.com/browserify/node-util) through [`which-typed-array`](https://github.com/browserify/node-util/blob/master/package.json#L18) and [`is-typed-array`](https://github.com/browserify/node-util/blob/master/package.json#L16)), evaluating `global` throws an error, as the browser's equivalent is `globalThis`.

How can we make this package, as well as those other two, run on the browser?

**Comment by ljharb** [comment]
A node module bundler that isn't broken (browserify, webpack 4 or below) always polyfills node globals, so `global` should in fact become `window` automatically.

If you're using webpack 5, for example, which is broken in this way, you'll have to fix your webpack config to do this polyfilling.

**Comment by aryzing** [comment]
Wouldn't it be easier for users to have a browser-compatible module? You're right in that there's quite a few of them and their behaviors differ. The new wave of development focused bundlers like snowpack and vite don't offer this configuration option (yet?). 

The one thing they all have in common though is respecting the `browser` field in `package.json`. Is using this field not a good solution?

**Comment by ljharb** [comment]
This is a node module, a CJS one. Browsers don't support CJS. A native ESM module would be easier for browser users, but not any easier for node users, and since a node module might use `require` and have dependencies, it's not practical or safe to rely on using it without a bundler.

I could certainly duplicate the one JS file in this repo, and change `global` to `window`, and use the browser field, but the purpose of that field isn't to fix broken bundlers, it's to provide reasonable browser code when the _existing_ code can't reasonably work in browsers. This code can do so, assuming the node module bundler is properly bundling node modules.

You can also "fix" it with `window.global = window` in your own code, if you don't want to fix your webpack config.

**Comment by aryzing** [comment]
> You can also "fix" it with window.global = window in your own code, if you don't want to fix your webpack config.

Thanks for the tip
